### PR TITLE
fix: update ember-cli-babel

### PR DESCRIPTION
**Pull request by knownasilya**
v5 was deprecated

### CODE REVIEW

**Comment by tim-evans** [comment]
@knownasilya I'm tempted to archive this repo, since there hasn't been a strong champion for this. I'd recommend looking at ember-file-upload for a more well supported addon in the same vein

**Comment by tim-evans** [comment]
If you'd like, I can give you admin access here to manage this.

**Comment by knownasilya** [comment]
I've had it on my list to switch over, but haven't had time recently. I'd be fine with admin rights, but would only help merge PRs and cut releases probably, until it's officially deprecated.

**Comment by tim-evans** [comment]
Release 1.13.20

**Pull request merged**
